DROP DATABASE MOVIE;
CREATE DATABASE MOVIE;
USE MOVIE;
-- SELECT * FROM USERS;
-- INSERT INTO USERS(ID, USERNAME, FIRST_NAME, LAST_NAME, DOB, GENDER, ADDRESS, PHONE, EMAIL, USER_ROLE, SCORE) VALUES ('USE0', 'mduc017', 'Đức', 'Trương', '2000-02-07', 'M', 'abc', '0934832405', 'mduc017@gmail.com', 'SUBSCRIBER', 0);

CREATE TABLE USERS(
	ID VARCHAR(10) NOT NULL,
    USERNAME VARCHAR(255) UNIQUE, -- TEN TAI KHOAN
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255) NOT NULL,
    -- FULLNAME VARCHAR(255),
    DOB DATETIME,	-- date of birth
    GENDER VARCHAR(3),
    ADDRESS VARCHAR(255),
    PHONE VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    USER_ROLE VARCHAR(255) NOT NULL,
    SCORE INT,
    CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY(ID)
) ENGINE = InnoDB;

CREATE TABLE MOVIES(
	ID VARCHAR(10) NOT NULL UNIQUE,
	TITLE VARCHAR(255) NOT NULL,
    OVERVIEW TEXT,
    RELEASE_DATE DATE NOT NULL,
    LANGUAGE VARCHAR(50) NOT NULL,
    DURATION INT NOT NULL,
    MOVIE_STATUS VARCHAR(20) NOT NULL,
    VIEW_COUNT INT,
    POSTER_PATH VARCHAR(50),
    BACKDROP_PATH VARCHAR(50),
    REVENUE DOUBLE,
    TAGLINE TEXT,
    VOTE_COUNT INT NOT NULL,
    VOTE_AVERAGE FLOAT NOT NULL,
    CONSTRAINT PK_MOVIE_ID PRIMARY KEY(ID)
) ENGINE = InnoDB;
CREATE TABLE GENRES(
	ID VARCHAR(10),
    NAME VARCHAR(50),
    CONSTRAINT PK_GENRE_ID PRIMARY KEY(ID)
) ENGINE = InnoDB;
CREATE TABLE MOVIE_GENRES(
	MOVIE_ID VARCHAR(10),
    GENRE_ID VARCHAR(10),
    CONSTRAINT PK_MOVIE_GENRES_ID PRIMARY KEY (MOVIE_ID, GENRE_ID),
    CONSTRAINT FK_MOVIE_GENRES_MOVIE_ID FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(ID),
    CONSTRAINT FK_MOVIE_GENRES_GENRE_ID FOREIGN KEY (GENRE_ID) REFERENCES MOVIES(ID)
) ENGINE = InnoDB;
CREATE TABLE PRODUCTION_COMPANIES (
	ID VARCHAR(10),
    NAME VARCHAR(50),
    CONSTRAINT PK_PRODUCTION_COMPANIES_ID PRIMARY KEY (ID)
) ENGINE = InnoDB;
CREATE TABLE MOVIE_PRODUCTION_COMPANIES (
	MOVIE_ID VARCHAR(10),
    PRODUCTION_COMPANY_ID VARCHAR(10),
    CONSTRAINT PK_MOVIE_PRODUCTION_COMPANIES_ID PRIMARY KEY (MOVIE_ID, PRODUCTION_COMPANY_ID),
    CONSTRAINT FK_MOVIE_PRODUCTION_COMPANIES_MOVIE_ID FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(ID),
    CONSTRAINT FK_MOVIE_PRODUCTION_COMPANIES_PRODUCTION_COMPANY_ID FOREIGN KEY (PRODUCTION_COMPANY_ID) REFERENCES PRODUCTION_COMPANIES(ID)
) ENGINE = InnoDB;
-- INSERT INTO MOVIES VALUES ('MOV4', 'ABC', 'ABC', '2000-07-02', 'abc', 10, 'abc', 1);
CREATE TABLE REVIEW(
	USER_ID VARCHAR(10) NOT NULL,
    MOVIE_ID VARCHAR(10) NOT NULL,
    RATING INT,
    REVIEW_COMMENT TEXT,
    REVIEW_DATE DATETIME,
    CONSTRAINT PK_REVIEW_ID PRIMARY KEY(USER_ID, MOVIE_ID),
    CONSTRAINT FK_REVIEW_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_REVIEW_MOVIE_ID FOREIGN KEY(MOVIE_ID) REFERENCES MOVIES(ID)
) ENGINE = InnoDB;

CREATE TABLE MOVIE_THEATERS(
	ID VARCHAR(10) NOT NULL UNIQUE,
    MT_NAME VARCHAR(255) NOT NULL,	-- TEN RAP CHIEU PHIM
    TICKET_COUNT INT,		-- SỐ VÉ ĐÃ BÁN
    ADDRESS VARCHAR(255),
    MT_AREA VARCHAR(255) NOT NULL,
    CONSTRAINT PK_MT_ID PRIMARY KEY(ID)
) ENGINE = InnoDB;

CREATE TABLE SCREEN_ROOMS(
	ID VARCHAR(10) NOT NULL UNIQUE,
    SR_NAME VARCHAR(255) NOT NULL,
    AMOUNT_SEAT INT,
    CONSTRAINT PK_SR_ID PRIMARY KEY(ID)
) ENGINE = InnoDB;

CREATE TABLE SEATS(
	ID VARCHAR(10) NOT NULL UNIQUE,
    SCREEN_ROOM_ID VARCHAR(10) NOT NULL,
    CATEGORY VARCHAR(50),
    SEAT_STATUS VARCHAR(10) NOT NULL,
    CONSTRAINT PK_SEAT_ID PRIMARY KEY(ID),
    CONSTRAINT FK_SEATS_SR_ID FOREIGN KEY(SCREEN_ROOM_ID) REFERENCES SCREEN_ROOMS(ID)
) ENGINE = InnoDB;

CREATE TABLE AUTHENTICATION(
    ID VARCHAR(10) NOT NULL, -- TAI KHOAN
    PASS VARCHAR(255) NOT NULL,
    CONSTRAINT PK_ACCOUNT_ID_PASS PRIMARY KEY(ID, PASS),
	CONSTRAINT FK_ACCOUNT_ID FOREIGN KEY(ID) REFERENCES USERS(ID)
) ENGINE = InnoDB;

CREATE TABLE SCHEDULES(
	ID VARCHAR(10) NOT NULL UNIQUE,
    MOVIE_ID VARCHAR(10) NOT NULL,
    MOVIE_THEATER_ID VARCHAR(10) NOT NULL,
    SCREEN_ROOM_ID VARCHAR(10) NOT NULL,
    START_DATE DATETIME,
    END_DATE DATETIME,
    CONSTRAINT PK_SCHEDULE_ID PRIMARY KEY(ID),
    CONSTRAINT FK_SCHEDULE_MOVIE_ID FOREIGN KEY(MOVIE_ID) REFERENCES MOVIES(ID),
    CONSTRAINT FK_SCHEDULE_MOVIE_THEATER_ID FOREIGN KEY(MOVIE_THEATER_ID) REFERENCES MOVIE_THEATERS(ID),
    CONSTRAINT FK_SCHEDULE_SCREEN_ROOM_ID FOREIGN KEY(SCREEN_ROOM_ID) REFERENCES SCREEN_ROOMS(ID)
) ENGINE = InnoDB;

CREATE TABLE TICKETS(
	ID VARCHAR(10) NOT NULL UNIQUE,
    MOVIE_ID VARCHAR(10) NOT NULL,
    SEAT_ID VARCHAR(10) NOT NULL,
    SCHEDULE_ID VARCHAR(10) NOT NULL,
    CONSTRAINT PK_TICKET_ID PRIMARY KEY(ID),
    CONSTRAINT FK_TICKET_MOVIE_ID FOREIGN KEY(MOVIE_ID) REFERENCES MOVIES(ID),
    CONSTRAINT FK_TICKET_SEAT_ID FOREIGN KEY(SEAT_ID) REFERENCES SEATS(ID),
    CONSTRAINT FK_TICKET_SCHEDULE_ID FOREIGN KEY(SCHEDULE_ID) REFERENCES SCHEDULES(ID)
) ENGINE = InnoDB;

CREATE TABLE ITEMS(
	ID VARCHAR(10) NOT NULL UNIQUE,
    ITEM_NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,		-- LOAI ITEM: NUOC, BAP, ...
    PRICE DECIMAL(20),
    CONSTRAINT PK_ITEM_ID PRIMARY KEY(ID)
) ENGINE = InnoDB;

CREATE TABLE BOOK_TICKETS(
	ID VARCHAR(10),
	USER_ID VARCHAR(10) NOT NULL,
    BOOK_DATE DATETIME,
    AMOUNT INT,
    CONSTRAINT PK_BT_ID PRIMARY KEY(ID),
    CONSTRAINT FK_BT_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
) ENGINE = InnoDB;

CREATE TABLE BOOK_TICKET_MAP(
	BOOK_TICKET_ID VARCHAR(10) NOT NULL,
    TICKET_ID VARCHAR(10) NOT NULL,
    CONSTRAINT PK_BTM_ID PRIMARY KEY(BOOK_TICKET_ID, TICKET_ID),
    CONSTRAINT FK_BTM_BOOK_TICKET_ID FOREIGN KEY(BOOK_TICKET_ID) REFERENCES BOOK_TICKETS(ID),
    CONSTRAINT FK_BTM_TICKET_ID FOREIGN KEY(TICKET_ID) REFERENCES TICKETS(ID)
) ENGINE = InnoDB;

CREATE TABLE BOOK_ITEMS(
	ID VARCHAR(10),
	USER_ID VARCHAR(10) NOT NULL,
    AMOUNT INT,
    BOOK_DATE DATETIME,
    CONSTRAINT PK_BI_ID PRIMARY KEY(ID),
    CONSTRAINT FK_BI_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
) ENGINE = InnoDB;

CREATE TABLE BOOK_ITEM_MAP(
	BOOK_ITEM_ID VARCHAR(10) NOT NULL,
    ITEM_ID VARCHAR(10) NOT NULL,
    CONSTRAINT PK_BOOK_ITEM_MAP_ID PRIMARY KEY(BOOK_ITEM_ID, ITEM_ID),
    CONSTRAINT FK_BIM_BOOK_ITEM_ID FOREIGN KEY(BOOK_ITEM_ID) REFERENCES BOOK_ITEMS(ID),
    CONSTRAINT FK_BIM_ITEM_ID FOREIGN KEY(ITEM_ID) REFERENCES ITEMS(ID)
) ENGINE = InnoDB;

CREATE TABLE PROMOTIONS(
	ID VARCHAR(10) NOT NULL,
    PROMOTION_NAME VARCHAR(255),
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    PROMOTION_DESCRIPTION TEXT,
    DISCOUNT INT,
    CONSTRAINT PK_PROMOTION_ID PRIMARY KEY(ID)
) ENGINE = InnoDB;

CREATE TABLE PROMOTION_RELATIONSHIP(
	PROMOTION_ID VARCHAR(10) NOT NULL,
    USER_ID VARCHAR(10) NOT NULL,
    MOVIE_ID VARCHAR(10),
    MOVIE_THEATER_ID VARCHAR(10) NOT NULL,
    ITEM_ID VARCHAR(10),
    CONSTRAINT PK_PROMOTION_RELATIONSHIP PRIMARY KEY(PROMOTION_ID, USER_ID, MOVIE_ID, MOVIE_THEATER_ID, ITEM_ID),
    CONSTRAINT FK_PR_PROMOTION_ID FOREIGN KEY(PROMOTION_ID) REFERENCES PROMOTIONS(ID),
    CONSTRAINT FK_PR_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_PR_MOVIE_ID FOREIGN KEY(MOVIE_ID) REFERENCES MOVIES(ID),
    CONSTRAINT FK_PR_MOVIE_THEATER_ID FOREIGN KEY(MOVIE_THEATER_ID) REFERENCES MOVIE_THEATERS(ID),
    CONSTRAINT FK_PR_ITEM_ID FOREIGN KEY(ITEM_ID) REFERENCES ITEMS(ID)
) ENGINE = InnoDB;

CREATE TABLE PAYMENTS(
	ID VARCHAR(10) NOT NULL UNIQUE,
    PROMOTION_ID VARCHAR(10),
    BOOK_TICKET_ID VARCHAR(10) NOT NULL,
    BOOK_ITEM_ID VARCHAR(10) NOT NULL,
    USER_ID VARCHAR(10) NOT NULL,
    PAYMENT_DATE DATETIME NOT NULL,
    PAYMENT_METHOD VARCHAR(255) NOT NULL,	-- PHUONG THUC THANH TOAN
    TOTAL_MONEY DECIMAL(20) NOT NULL,
    CONSTRAINT PK_PAYMENT_ID PRIMARY KEY(ID),
    CONSTRAINT FK_PAYMENT_PROMOTION_ID FOREIGN KEY(PROMOTION_ID) REFERENCES PROMOTIONS(ID),
    CONSTRAINT FK_PAYMENT_BT_ID FOREIGN KEY(BOOK_TICKET_ID) REFERENCES BOOK_TICKETS(ID),
    CONSTRAINT FK_PAYMENT_BI_ID FOREIGN KEY(BOOK_ITEM_ID) REFERENCES BOOK_ITEMS(ID),
    CONSTRAINT FK_PAYMENT_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
) ENGINE = InnoDB;

